<?php
set_time_limit(0);
ini_set('memory_limit', "512M");
define('EOL', (PHP_SAPI == 'cli') ? PHP_EOL : '<br />');

require_once("includes/php_excel/Classes/PHPExcel.php");


// Create new PHPExcel object
//echo date('H:i:s') , " Create new PHPExcel object" , EOL;
$objPHPExcel = new PHPExcel();

// Set document properties
//echo date('H:i:s') , " Set document properties" , EOL;
$objPHPExcel->getProperties()->setCreator("Freeway LMS")
    ->setLastModifiedBy("Freeway LMS")
    ->setTitle("Lead Reports")
    ->setSubject("LMS Lead Reports")
    ->setDescription("Report Generated by LMS")
    ->setKeywords("LMS")
    ->setCategory("lms");


$ABC = array("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z","AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ");
//EXCEPTIONS
$extra_fields=array("org","date","hour","weekend","quarter");


$freports = $db->query("SELECT * FROM kpage_reports_fields_cv where id_report=:id", array("id" => $_SESSION['cv']["id_report_cv"]));
foreach ($extra_fields as $extra_field){
    $freports[]["name_field"]=$extra_field;
}

//$freports[]["name_field"] = "date";
//$freports[]["name_field"] = "hour";
//$freports[]["name_field"] = "weekend";
//$freports[]["name_field"] = "quarter";
//dd($freports);die;
$total_fields = count($freports);
//$total_fields=99;
$total_abc = count($ABC);
//echo "<hr>";
$t_indices = ceil($total_fields / $total_abc);
//echo "<hr>";
$indice = 1;
$cuenta = 0;
$sql_fields = "";
$objPHPExcel->setActiveSheetIndex(0);


for ($n = 1; $n <= $t_indices; $n++) {

    for ($a = 0; $a < $total_abc; $a++) {
        //echo $n;
        if ($n > 1) {
            //echo $ABC[($n-2)]."".$ABC[$a].$n."===".$freports[$cuenta]["name_field"];
            $columna = $ABC[($n - 2)] . "" . $ABC[$a] . $n;
        } else {
            //echo $ABC[$a].$n."===".$freports[$cuenta]["name_field"];
            $columna = $ABC[$a] . $n;
        }

        //echo $columna;
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue($columna, $freports[$cuenta]["name_field"]);
        //$objPHPExcel->getActiveSheet()->getStyle("$cell_name:$cell_name")->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle($columna)->getFont()->setBold(true);
        $f = $freports[$cuenta]["name_field"];
        //if (!($f == "date" || $f == "hour" || $f == "weekend" || $f == "quarter")) {
        if ($f == "phone") { //dar formato al campo phone "123-123-1234" - 
            // $f = "REPLACE(phone,'-','') as phone";
            $f = "concat( SUBSTR( REPLACE(phone,'-','') ,1,3), '-', SUBSTR(REPLACE(phone,'-',''),4,3), '-', SUBSTR(REPLACE(phone,'-',''),7,4)) as phone";
        }

        if ($f == "zip_code") { //Completar con ceros 
            $f = "CONCAT(' ', (LPAD(zip_code, 5, '0'))) as zip_code ";
        }
         
        if(!in_array($f,$extra_fields)){
            $sql_fields .= $f;
        }
        $cuenta++;
        if ($cuenta < ($total_fields - count($extra_fields))) {
            //if (!($f == "date" || $f == "hour" || $f == "weekend" || $f == "quarter")) {
            if(!in_array($f,$extra_fields)) {
                $sql_fields .= " , ";
            }
        }
        if ($cuenta == $total_fields) {
            $a = 56;
        }
        //echo "<br>";
    }
}
// Definiendo los where
$sql_where = "";
if (!empty($_SESSION['cv']["where"])) {

    $sql_where = " WHERE ";
    $awhere = $_SESSION['cv']["where"]["conditions"];
    //dd($awhere);
    $tsw = count($awhere);
    for ($w = 0; $w < $tsw; $w++) {
        $sql_where .= " " . $awhere[$w] . " ";
        if ($w < ($tsw - 1)) {
            $sql_where .= " AND ";
        }
    }
}

$sqltotal = "SELECT count(*) as total FROM lms_leads_commercial_vehicle $sql_where ";
$datatotal = $db->row($sqltotal);
$total_rows = $datatotal["total"];
//dd($total_fields);
$total_f = count($freports);
//echo "<hr>";
$total = $total_rows * $total_f;
//die;
if ($total >= 400000) {
    get_header();
    the_error("It is that your report is really, really big.", "Oh!, not that I can not do");
    ?>
    <p align="left"><a href="<?php echo _URLMODULE; ?>" class="loading-action-button medium-button primary-button">Generate
            a New Report</a></p><br>
    <?php
    get_footer();
    die;
}
$sql = "SELECT id as id_lead, 
DATE_FORMAT(last_update,'%m/%d/%Y') as 'date', 
time(last_update) as 'hour', 
WEEKOFYEAR(last_update) as 'weekend',
QUARTER(last_update) as 'quarter',
" . $sql_fields . " FROM lms_leads_commercial_vehicle $sql_where ORDER BY id_lead desc";
$data = $db->query($sql);
//dd($freports);
$fila = 1;


foreach ($data as $value) {
//
    $fila++;
    //echo $t_indices."=".$total_abc."<hr>";
    $cuenta = 0;
    for ($n = 1; $n <= $t_indices; $n++) {

        for ($a = 0; $a < $total_abc; $a++) {
            //echo $n;
            //echo $a."->";
            if ($n > 1) {
                //echo $ABC[($n-2)]."".$ABC[$a].$n."===".$freports[$cuenta]["name_field"];
                $columna = $ABC[($n - 2)] . "" . $ABC[$a] . $fila;
            } else {
                //echo $ABC[$a].$n."===".$freports[$cuenta]["name_field"];
                $columna = $ABC[$a] . $fila;
            }
            $ir = $freports[$a]["name_field"];
            //echo $columna."===".$ir."--->".$value[$ir];
            //dd($value);

            if ($ir == 'org') {
                $data = $db->row("SELECT organization_brand FROM rater_routing where media_code = :media_code", array('media_code' =>  $value['media_code']));                          
                $data['organization_brand'];
                $objPHPExcel->setActiveSheetIndex(0)
                ->setCellValue($columna, $data['organization_brand']);
            } else {
                $objPHPExcel->setActiveSheetIndex(0)
                ->setCellValue($columna, $value[$ir]);
            }
            

            // $objPHPExcel->setActiveSheetIndex(0)
            //     ->setCellValue($columna, $value[$ir]);

            //$f=$freports[$cuenta]["name_field"];
            $cuenta++;
            if ($cuenta == $total_fields) {
                $a = 28;
            }
            //echo "<br>";
        }
    }
    //die;
//			
}
// Rename worksheet
$objPHPExcel->getActiveSheet()->setTitle('Simple');
// Set active sheet index to the first sheet, so Excel opens this as the first sheet
/*$objPHPExcel->setActiveSheetIndex(0);

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
//echo __FILE__;
$file=__FILE__;
$objWriter->save(str_replace('.php', '.xlsx', $file));*/

// Redirect output to a client’s web browser (Excel5)
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="lms_report.xls"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header('Pragma: public'); // HTTP/1.0

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save('php://output');

die;

// Add some data
echo date('H:i:s'), " Add some data", EOL;
$objPHPExcel->setActiveSheetIndex(0)
    ->setCellValue('A1', 'Hello')
    ->setCellValue('B2', 'world!')
    ->setCellValue('C1', 'Hello')
    ->setCellValue('D2', 'world!');

// Miscellaneous glyphs, UTF-8
$objPHPExcel->setActiveSheetIndex(0)
    ->setCellValue('A4', 'Miscellaneous glyphs')
    ->setCellValue('A5', 'éàèùâêîôûëïüÿäöüç');


$objPHPExcel->getActiveSheet()->setCellValue('A8', "Hello\nWorld");
$objPHPExcel->getActiveSheet()->getRowDimension(8)->setRowHeight(-1);
$objPHPExcel->getActiveSheet()->getStyle('A8')->getAlignment()->setWrapText(true);


// Rename worksheet
echo date('H:i:s'), " Rename worksheet", EOL;
$objPHPExcel->getActiveSheet()->setTitle('Simple');


// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);


// Save Excel 2007 file
echo date('H:i:s'), " Write to Excel2007 format", EOL;
$callStartTime = microtime(true);

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save(str_replace('.php', '.xlsx', __FILE__));
$callEndTime = microtime(true);
$callTime = $callEndTime - $callStartTime;

echo date('H:i:s'), " File written to ", str_replace('.php', '.xlsx', pathinfo(__FILE__, PATHINFO_BASENAME)), EOL;
echo 'Call time to write Workbook was ', sprintf('%.4f', $callTime), " seconds", EOL;
// Echo memory usage
echo date('H:i:s'), ' Current memory usage: ', (memory_get_usage(true) / 1024 / 1024), " MB", EOL;


// Save Excel 95 file
echo date('H:i:s'), " Write to Excel5 format", EOL;
$callStartTime = microtime(true);

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save(str_replace('.php', '.xls', __FILE__));
$callEndTime = microtime(true);
$callTime = $callEndTime - $callStartTime;

echo date('H:i:s'), " File written to ", str_replace('.php', '.xls', pathinfo(__FILE__, PATHINFO_BASENAME)), EOL;
echo 'Call time to write Workbook was ', sprintf('%.4f', $callTime), " seconds", EOL;
// Echo memory usage
echo date('H:i:s'), ' Current memory usage: ', (memory_get_usage(true) / 1024 / 1024), " MB", EOL;


// Echo memory peak usage
echo date('H:i:s'), " Peak memory usage: ", (memory_get_peak_usage(true) / 1024 / 1024), " MB", EOL;

// Echo done
echo date('H:i:s'), " Done writing files", EOL;
echo 'Files have been created in ', getcwd(), EOL;
